### ISSUE TITLE
GUI Dark mode is not working well for MacOS.

### ISSUE THREAD

**Issue by iamwatchdogs** [iamwatchdogs/Calculator_GUI#2]
The Dark-themed GUI in Windows and Linux environments is not the same as it is for MacOS, the button background colour is the same numbers which makes it hard to recognise the buttons.

| Windows | Linux *(Ubuntu)* | MacOs |
| --- | --- | --- |
| <img alt="Windows Output" src="https://github.com/iamwatchdogs/Calculator_GUI/assets/49478000/70f5bff6-669c-4806-8357-7a90c5ae6dce" width="420" > | <img alt="Ubuntu Output" src="https://github.com/iamwatchdogs/Calculator_GUI/assets/49478000/35d8b6da-2ee6-44ea-a76a-b58fb9d64f4b" width="450"> | <img alt="MacOS Output" src="https://github.com/iamwatchdogs/Calculator_GUI/assets/49478000/801a557f-705e-494c-bed4-0427bd8863c0" width="450">  |

## Tasks

- [ ] Find the cause of this issue in [CalculatorView.java](../blob/main/src/calculator/CalculatorView.java "Goto CalculatorView.java").
- [ ] Fix the issue without disturbing other code.
- [ ] Document the bug within the PR.
